trigger:
- master

pool:
  vmImage: 'macOS-10.13'

name: $(Date:yyyyMMdd)$(Rev:r)
steps:
- task: ShellScript@2
  inputs:
    scriptPath: build.sh

- task: CopyFiles@2
  inputs:
    SourceFolder: './'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'
